### PUT request to Update patient by id
PUT http://lb-91c6babe.elb.localhost.localstack.cloud:4004/api/patients/a64d9a3a-22c5-4ff6-9036-3a5322652578
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "John",
  "email": "jae.smith@example.com",
  "address": "123 Main St, Springfield",
  "dateOfBirth": "1985-06-15"
}
###